server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: users-status-check
        uri: lb://users-ws
        predicates:
        - Path=/users-ws/user/status
        - Method=GET
        filters:
        - RewritePath=/users-ws/(?<segment>.*), /api/$\{segment}
      - id: users-create
        uri: lb://users-ws
        predicates:
          - Path=/users-ws/user
          - Method=POST
        filters:
          - RewritePath=/users-ws/(?<segment>.*), /api/$\{segment}
